### ISSUE TITLE
Some numbers don't look quite right

### ISSUE THREAD

**Issue by 0dinD** [MiniDigger/paperstats#28]
I was looking at [the stats for 1.20.2](https://minidigger.github.io/paperstats/#1.20.2) and noticed some funny looking numbers :thinking: :

![image](https://github.com/MiniDigger/paperstats/assets/52179873/1ac7a708-d158-4444-99ed-545cf9cffa66)

A similar case can be seen for 1.18.1:

![image](https://github.com/MiniDigger/paperstats/assets/52179873/2d94156f-5fcc-41f4-8a53-93045978ea31)

It looks like either Bukkit/Spigot is underrepresented or Paper is overrepresented in the statistics (or both). Maybe this is more of an issue with bStats? For example, what if some Paper servers (forks?) report as running Paper, but not as running Bukkit/Spigot? Something like that could explain why Bukkit/Spigot seems underrepresented in the statistics. But I'm not really sure how the bStats statistics are reported by the various server implementations.

**Comment by MiniDigger** [comment]
this is known. 
the paper number tracks all paper servers, the spigot number only spigot servers with bstats plugins. since spigot doesnt track to bstats itself, this is the best we can do, but its good enough.
